# Práctica / Proyecto — Sistema de recomendación con embeddings modernos

## Contexto

A lo largo de la asignatura hemos trabajado con enfoques clásicos de sistemas de recomendación:
- recomendadores simples,
- recomendadores basados en contenido,
- filtrado colaborativo,
- e híbridos.

En esta práctica se propone dar un paso más y explorar si **los embeddings obtenidos con IA moderna** pueden ofrecer una representación más rica de los ítems y, en consecuencia, recomendaciones de mayor calidad.

La idea central del proyecto es que diseñéis, implementéis y evaluéis un **recomendador basado en embeddings** y lo comparéis con **uno o varios enfoques tradicionales**.

---

## Idea general

No se trata solo de “usar embeddings porque sí”.

Queremos que penséis como un equipo de Data Science que debe responder, con evidencias, a preguntas como:

- ¿Qué información del dataset merece la pena usar?
- ¿Cómo conviene convertir esa información a texto antes de obtener embeddings?
- ¿Mejora realmente el sistema frente a enfoques más sencillos?
- ¿En qué escenarios mejora, en cuáles no, y por qué?
- ¿Qué métricas y protocolo experimental son razonables para defender esa conclusión?

---

## Libertad de implementación

Podéis elegir la tecnología que queráis para obtener embeddings, por ejemplo:
- APIs externas,
- modelos open-source en local,
- herramientas tipo servidor local de modelos,
- u otras alternativas equivalentes.

También podéis usar embeddings generados por un modelo generalista o por un modelo específico de retrieval / embeddings.

Lo importante no es la marca de la herramienta, sino:
1. que expliquéis bien vuestra decisión,
2. que el pipeline sea reproducible,
3. y que la comparación experimental esté bien planteada.

# Enunciado

## Tarea principal

Desarrollad un **sistema de recomendación basado en embeddings modernos** y comparadlo con **uno o varios sistemas tradicionales** sobre un dataset elegido por vuestro equipo.

El trabajo debe incluir, como mínimo:

### 1. Elección del dataset
Seleccionad un dataset adecuado para recomendación. El dominio es libre:
- películas,
- libros,
- videojuegos,
- música,
- productos,
- noticias,
- cursos,
- recetas,
- alojamientos,
- etc.

El dataset elegido debe permitir al menos una de estas dos posibilidades:
- construir recomendaciones a partir de **contenido / metadatos / texto**, o
- combinar contenido con algún tipo de **interacción usuario-ítem** si disponéis de ella.

### 2. Diseño de la representación del ítem
Debéis decidir **qué información incluir** para representar cada ítem.

Por ejemplo, según el dataset, podríais usar:
- título,
- descripción,
- categorías,
- tags,
- autor / director / marca,
- actores,
- keywords,
- atributos técnicos,
- precio,
- reseñas,
- combinaciones de varias columnas,
- etc.

No basta con concatenar columnas sin pensar.

Debéis justificar:
- qué columnas habéis escogido,
- cuáles habéis descartado,
- cómo las habéis limpiado,
- y cómo las habéis convertido en un único string o estructura textual antes de obtener embeddings.

### 3. Recomendador basado en embeddings
Implementad un sistema que use embeddings para recomendar ítems.

Algunas posibilidades:
- similitud ítem–ítem,
- perfil de usuario construido a partir de ítems consumidos,
- consulta textual + retrieval semántico,
- enfoque híbrido entre contenido y señales de interacción.

### 4. Comparación con métodos más tradicionales
Debéis implementar y comparar vuestro enfoque con **uno o varios baseline** más sencillos.

Ejemplos de baseline razonables (los vistos en clase):
- recomendador simple por popularidad o score,
- TF-IDF + similitud coseno,
- CountVectorizer / bag-of-words,
- metadata soup clásica,
- filtrado colaborativo user-based o item-based,
- kNN,
- SVD / matrix factorization,
- híbrido simple.

### 5. Evaluación
Debéis investigar y justificar **cómo evaluar** el sistema.

No hay una única respuesta correcta: la evaluación depende del tipo de recomendación que planteéis.

Por tanto, tendréis que decidir:
- qué partición de datos es razonable,
- qué escenario de test estáis simulando,
- qué métricas son adecuadas,
- y cómo interpretar si hay mejora real o no.

### 6. Discusión crítica
Además de mostrar resultados, debéis reflexionar sobre:
- retos encontrados,
- limitaciones del enfoque,
- coste computacional,
- dependencia del texto / metadatos,
- cold start,
- calidad de embeddings,
- sensibilidad a cómo construís el string,
- escenarios donde el método moderno ayuda,
- y escenarios donde un baseline clásico puede seguir siendo mejor.

# Restricciones mínimas del proyecto

## Mínimos obligatorios

El trabajo **debe** contener como mínimo lo siguiente:

- Un dataset real elegido por el equipo.
- Un análisis exploratorio breve pero útil del dataset.
- Un pipeline de preparación de datos reproducible.
- Un sistema de recomendación basado en embeddings modernos.
- Al menos **un baseline tradicional** bien implementado.
- Una comparación cuantitativa y una comparación cualitativa.
- Una sección final de conclusiones.

## Recomendación fuerte

Aunque el mínimo es **1 baseline**, es muy recomendable incluir **2 baselines**:
- uno muy sencillo,
- y otro más competitivo.

Ejemplo:
- baseline 1: popularidad / score,
- baseline 2: TF-IDF o filtrado colaborativo,
- modelo final: embeddings modernos.

# Sugerencias para elegir el dataset

## Qué buscamos en un buen dataset para esta práctica

Idealmente, vuestro dataset debería tener:
- suficientes ítems para que recomendar tenga sentido,
- metadatos o texto útiles,
- cierta variedad semántica,
- y, si es posible, alguna señal de interacción o preferencia.

## Ejemplos de datasets adecuados

Podéis buscar datasets en:
- Kaggle,
- Hugging Face Datasets,
- MovieLens,
- Amazon Reviews,
- Goodbooks,
- datasets de Spotify,
- Steam,
- Last.fm,
- artículos / noticias,
- catálogos de productos,
- u otras fuentes abiertas.

## Consejo importante

No elijáis un dataset gigantesco si luego no podéis procesarlo ni evaluarlo bien.

En esta práctica suele valer más:
- un dataset **moderado**,
- bien entendido,
- bien limpiado,
- y bien evaluado,

que un dataset enorme con un pipeline incompleto o poco defendible.

In [1]:
# Espacio de trabajo: elección y carga del dataset

# TODO:
# - indicar la fuente del dataset -> "jahnavipaliwal/video-game-reviews-and-ratings"
# - cargar los datos
import pandas as pd
dataset = pd.read_csv("data/video_game_reviews.csv")
dataset = dataset.head(10000)

# - mostrar su estructura básica
dataset.info()
# - dejar claro qué representa un ítem y, si aplica, qué representa un usuario
games = dataset["Game Title"].value_counts()
games

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Game Title               10000 non-null  str
 1   User Rating              10000 non-null  float64
 2   Age Group Targeted       10000 non-null  str
 3   Price                    10000 non-null  float64
 4   Platform                 10000 non-null  str
 5   Requires Special Device  10000 non-null  str
 6   Developer                10000 non-null  str
 7   Publisher                10000 non-null  str
 8   Release Year             10000 non-null  int64
 9   Genre                    10000 non-null  str
 10  Multiplayer              10000 non-null  str
 11  Game Length (Hours)      10000 non-null  float64
 12  Graphics Quality         10000 non-null  str
 13  Soundtrack Quality       10000 non-null  str
 14  Story Quality            10000 non-null  str
 15  User Review Text         10000 non-null  str
 16  Game Mode                10000 non-null  str
 17  Min Number of Players    10000 non-null  int64
dtypes: float64(3), int64(2), str(13)
memory usage: 1.4 MB

Game Title
1000-Piece Puzzle                          292
Hitman 3                                   288
Street Fighter V                           274
Tomb Raider (2013)                         265
Grand Theft Auto V                         264
Half-Life: Alyx                            263
Call of Duty: Modern Warfare 2             263
Mario Kart 8 Deluxe                        263
The Witcher 3: Wild Hunt                   262
Overwatch 2                                261
FIFA 24                                    261
Ghost of Tsushima                          260
Pillars of Eternity II: Deadfire           258
Minecraft                                  256
The Legend of Zelda: Breath of the Wild    256
Tekken 7                                   256
Pokémon Scarlet & Violet                   256
Super Smash Bros. Ultimate                 256
Bioshock Infinite                          254
Fall Guys                                  253
Fortnite                                   252
Tetris                                     252
Counter-Strike: Global Offensive           251
Just Dance 2024                            248
Super Mario Odyssey                        244
Spelunky 2                                 241
Sid Meier’s Civilization VI                239
Hades                                      239
Animal Crossing: New Horizons              238
Portal 2                                   237
Cuphead                                    236
Halo Infinite                              235
Kingdom Hearts III                         235
The Elder Scrolls V: Skyrim                232
Stardew Valley                             232
The Sims 4                                 231
Among Us                                   231
League of Legends                          226
Rocket League                              224
Red Dead Redemption 2                      216
Name: count, dtype: int64

# 1. Definición del problema de recomendación

Antes de programar, definid con claridad **qué problema vais a resolver**.

## Preguntas que debéis responder

1. ¿Qué es un ítem en vuestro problema?
2. ¿Existe usuario explícito o vais a trabajar solo con similitud entre ítems?
3. ¿Qué significa “recomendar bien” en vuestro caso?
4. ¿Queréis recomendar:
   - ítems parecidos a uno dado,
   - top-N para un usuario,
   - retrieval semántico a partir de una consulta,
   - o una combinación?
5. ¿Qué limitaciones tiene vuestro dataset para ese objetivo?

## Entregable de esta sección

Redactad una breve explicación del escenario de recomendación que vais a modelar.

The recommendation problem addressed in this project focuses on suggesting video games based on their similarity to other games in the dataset. Each item corresponds to a video game described by several attributes, including genre, platform, and user reviews. Although the dataset contains user ratings and textual reviews that provide insight into how games are evaluated, it does not include explicit user identifiers. As a result, the system will primarily rely on similarities between items, using metadata and review text to determine how closely related different games are. A successful recommendation is one in which the suggested games align with a user’s preferences, for example by sharing similar genres, gameplay characteristics, or supported platforms. The system will therefore follow an item-to-item recommendation approach, where given a specific game, it returns the Top-N most similar games based on their textual descriptions and metadata. However, the dataset presents certain limitations, such as the absence of explicit user identifiers and limited contextual information about players, which makes it difficult to implement traditional collaborative filtering methods.

# 2. Análisis exploratorio y comprensión del dato

Realizad un EDA breve, orientado al problema.

No queremos un EDA enciclopédico, sino uno útil para decidir cómo construir el recomendador.

## Posibles aspectos sugeridos

- número de ítems,
- columnas disponibles,
- porcentaje de nulos,
- longitud de textos,
- frecuencia de categorías,
- distribución de ratings o interacciones (si existen),
- duplicados,
- problemas de calidad,
- idiomas mezclados,
- campos ruidosos,
- atributos muy informativos frente a atributos irrelevantes.

## Objetivo de esta sección

Que el EDA os ayude a responder:
- qué información merece la pena usar,
- qué hay que limpiar,
- y qué baseline tiene sentido construir.

In [2]:
# cols
dataset.info()

# nulls
nulls = dataset.isna().sum()
nulls

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Game Title               10000 non-null  str
 1   User Rating              10000 non-null  float64
 2   Age Group Targeted       10000 non-null  str
 3   Price                    10000 non-null  float64
 4   Platform                 10000 non-null  str
 5   Requires Special Device  10000 non-null  str
 6   Developer                10000 non-null  str
 7   Publisher                10000 non-null  str
 8   Release Year             10000 non-null  int64
 9   Genre                    10000 non-null  str
 10  Multiplayer              10000 non-null  str
 11  Game Length (Hours)      10000 non-null  float64
 12  Graphics Quality         10000 non-null  str
 13  Soundtrack Quality       10000 non-null  str
 14  Story Quality            10000 non-null  str
 15  User Review Text         10000 non-null  str
 16  Game Mode                10000 non-null  str
 17  Min Number of Players    10000 non-null  int64
dtypes: float64(3), int64(2), str(13)
memory usage: 1.4 MB

Game Title                 0
User Rating                0
Age Group Targeted         0
Price                      0
Platform                   0
Requires Special Device    0
Developer                  0
Publisher                  0
Release Year               0
Genre                      0
Multiplayer                0
Game Length (Hours)        0
Graphics Quality           0
Soundtrack Quality         0
Story Quality              0
User Review Text           0
Game Mode                  0
Min Number of Players      0
dtype: int64

In [3]:
duplicates = dataset[dataset.duplicated()]
duplicates

Empty DataFrame
Columns: [Game Title, User Rating, Age Group Targeted, Price, Platform, Requires Special Device, Developer, Publisher, Release Year, Genre, Multiplayer, Game Length (Hours), Graphics Quality, Soundtrack Quality, Story Quality, User Review Text, Game Mode, Min Number of Players]
Index: []

In [4]:
import numpy as np
# reviews per items
games = dataset["Game Title"].value_counts()
games

Game Title
1000-Piece Puzzle                          292
Hitman 3                                   288
Street Fighter V                           274
Tomb Raider (2013)                         265
Grand Theft Auto V                         264
Half-Life: Alyx                            263
Call of Duty: Modern Warfare 2             263
Mario Kart 8 Deluxe                        263
The Witcher 3: Wild Hunt                   262
Overwatch 2                                261
FIFA 24                                    261
Ghost of Tsushima                          260
Pillars of Eternity II: Deadfire           258
Minecraft                                  256
The Legend of Zelda: Breath of the Wild    256
Tekken 7                                   256
Pokémon Scarlet & Violet                   256
Super Smash Bros. Ultimate                 256
Bioshock Infinite                          254
Fall Guys                                  253
Fortnite                                   252
Tetris                                     252
Counter-Strike: Global Offensive           251
Just Dance 2024                            248
Super Mario Odyssey                        244
Spelunky 2                                 241
Sid Meier’s Civilization VI                239
Hades                                      239
Animal Crossing: New Horizons              238
Portal 2                                   237
Cuphead                                    236
Halo Infinite                              235
Kingdom Hearts III                         235
The Elder Scrolls V: Skyrim                232
Stardew Valley                             232
The Sims 4                                 231
Among Us                                   231
League of Legends                          226
Rocket League                              224
Red Dead Redemption 2                      216
Name: count, dtype: int64

In [5]:
# make sure user rating goes from 1-5
dataset["User Rating"] = dataset["User Rating"] / 10
dataset

,Game Title,User Rating,Age Group Targeted,Price,Platform,Requires Special Device,Developer,Publisher,Release Year,Genre,Multiplayer,Game Length (Hours),Graphics Quality,Soundtrack Quality,Story Quality,User Review Text,Game Mode,Min Number of Players
0,Grand Theft Auto V,3.64,All Ages,41.41,PC,No,Game Freak,Innersloth,2015,Adventure,No,55.3,Medium,Average,Poor,"Solid game, but too many bugs.",Offline,1
1,The Sims 4,3.83,Adults,57.56,PC,No,Nintendo,Electronic Arts,2015,Shooter,Yes,34.6,Low,Poor,Poor,"Solid game, but too many bugs.",Offline,3
2,Minecraft,2.68,Teens,44.93,PC,Yes,Bungie,Capcom,2012,Adventure,Yes,13.9,Low,Good,Average,"Great game, but the graphics could be better.",Offline,5
3,Bioshock Infinite,3.84,All Ages,48.29,Mobile,Yes,Game Freak,Nintendo,2015,Sports,No,41.9,Medium,Good,Excellent,"Solid game, but the graphics could be better.",Online,4
4,Half-Life: Alyx,3.01,Adults,55.49,PlayStation,Yes,Game Freak,Epic Games,2022,RPG,Yes,13.2,High,Poor,Good,"Great game, but too many bugs.",Offline,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Animal Crossing: New Horizons,3.09,All Ages,50.16,PC,No,Game Freak,Innersloth,2014,Strategy,No,17.7,Medium,Good,Excellent,"Solid game, but too many bugs.",Offline,2
9996,Tekken 7,2.06,Adults,21.56,Nintendo Switch,No,Game Freak,Capcom,2020,Shooter,Yes,35.3,Medium,Excellent,Average,"Disappointing game, but the graphics could be ...",Online,7
9997,Call of Duty: Modern Warfare 2,3.06,Kids,47.68,PlayStation,Yes,Game Freak,Epic Games,2013,RPG,No,20.8,High,Poor,Poor,"Disappointing game, but the graphics could be ...",Offline,7
9998,Pokémon Scarlet & Violet,2.11,Teens,30.01,Xbox,Yes,Game Freak,Innersloth,2016,Puzzle,No,18.3,Low,Average,Good,"Great game, but the graphics could be better.",Offline,2
9999,Fall Guys,3.89,Adults,46.84,Nintendo Switch,Yes,Innersloth,Innersloth,2017,Party,Yes,52.6,High,Average,Excellent,"Solid game, but the gameplay is amazing.",Online,5

In [6]:
# text length
reviews = dataset["User Review Text"].str.len()
reviews.describe()

count    10000.00000
mean        40.82310
std          7.06337
min         30.00000
25%         32.00000
50%         40.00000
75%         45.00000
max         53.00000
Name: User Review Text, dtype: float64

In [7]:
import plotly.express as px

genres = dataset["Genre"].value_counts().reset_index()
genres.columns = ["Genre", "Count"]

fig = px.bar(
    genres,
    x="Genre",
    y="Count",
    title="Distribution of games by Genre"
)

fig.show()

In [8]:
rating_genre = dataset.groupby("Genre")["User Rating"].mean().reset_index()

fig = px.bar(
    rating_genre,
    x="Genre",
    y="User Rating",
    title="Average User Rating by Genre"
)

fig.show()

In [9]:
fig = px.histogram(
    dataset,
    x="User Rating",
    nbins=20,
    title="Distribution of User Ratings"
)

fig.show()

In [10]:
fig = px.histogram(
    dataset,
    x="Platform",
    nbins=20,
    title="Distribution of platforms"
)

fig.show()

In [11]:
quality = dataset["Graphics Quality"].value_counts()
quality

Graphics Quality
Medium    2551
Low       2488
High      2483
Ultra     2478
Name: count, dtype: int64

In [12]:
age = dataset["Age Group Targeted"].value_counts()
age

Age Group Targeted
Kids        2590
Adults      2540
Teens       2494
All Ages    2376
Name: count, dtype: int64

In [13]:
fig = px.box(
    dataset,
    x="Release Year",
    y="User Rating",
    title="User rating by release year"
)

fig.show()

In [14]:
fig = px.histogram(
    dataset,
    x="Release Year",
    nbins=50,
    title="Distribution of video games by release year"
)

fig.show()

After performing an analysis on the data, we define out most informative attributed that will help us with our recommendation system to be the following:
- Game Title
- User Rating
- Age Group Targeted
- Price
- Platform,
- Release Year
- Genre
- Graphics Quality
- Story Quality
- User Review Text (used for semantic representation)

# 3. Ingeniería de representación del ítem

Esta es una de las partes más importantes de la práctica.

Los embeddings no “hacen magia” si la entrada está mal planteada.

## Tarea

Debéis diseñar **una o varias estrategias de representación textual** del ítem.

### Ejemplos de preguntas útiles

- ¿Uso solo la descripción?
- ¿Añado título al principio?
- ¿Repito o pondero ciertos campos?
- ¿Convierto listas de tags en lenguaje natural?
- ¿Mantengo campos estructurados como texto tipo `género: acción | drama`?
- ¿Incluyo atributos numéricos transformados a texto?
- ¿Merece la pena concatenar todo o genera ruido?
- ¿Es mejor una representación corta y precisa o una más rica y larga?

## Requisito obligatorio

Debéis probar **al menos una estrategia razonada** de construcción del string de entrada.

## Recomendación fuerte

Probad **dos o más variantes** y comentad:
- cuál parece funcionar mejor,
- cuál es más interpretable,
- y cuál introduce más ruido.

## Ejemplos de variantes posibles

- Variante A: título + descripción.
- Variante B: título + descripción + categorías.
- Variante C: título + descripción + categorías + tags + autor.
- Variante D: formato más “natural” en frases.
- Variante E: formato más “estructurado” tipo campos etiquetados.

In [15]:
# TODO:
# construir una o varias funciones que conviertan cada ítem en un string
# justificar las decisiones tomadas

# Objetivos de aprendizaje

Al finalizar esta práctica deberíais ser capaces de:

1. Diseñar un problema de recomendación a partir de un dataset real.
2. Construir una representación útil de los ítems a partir de texto, metadatos o ambas cosas.
3. Implementar un recomendador moderno basado en embeddings.
4. Compararlo con métodos tradicionales de recomendación.
5. Diseñar una evaluación razonable.
6. Analizar críticamente resultados, limitaciones, retos y posibles mejoras.

In [16]:
import pandas as pd

def create_dict_string(row):
    return (
        f"Title: {row['Game Title']},"
        f"User Rating: {row['User Rating']}/5,"
        f"Target Audience: {row['Age Group Targeted']},"
        f"Price: ${row['Price']},"
        f"Platform: {row['Platform']},"
        f"Requires Special Device: {row['Requires Special Device']},"
        f"Developer: {row['Developer']},"
        f"Publisher: {row['Publisher']},"
        f"Release Year: {row['Release Year']},"
        f"Genre: {row['Genre']},"
        f"Multiplayer: {row['Multiplayer']},"
        f"Game Length: {row['Game Length (Hours)']} hours,"
        f"Graphics Quality: {row['Graphics Quality']},"
        f"Soundtrack Quality: {row['Soundtrack Quality']},"
        f"Story Quality: {row['Story Quality']},"
        f"Game Mode: {row['Game Mode']},"
        f"Minimum Players: {row['Min Number of Players']}."
        f"User Review: {row['User Review Text']}"
    )

def create_text_string(row):
    return (
        f"{row['Game Title']} is a {row['Genre']} game for {row['Platform']}, it was "
        f"released in {row['Release Year']} by the developer {row['Developer']} and the publisher {row['Publisher']}. "
        f"It is targeted towards the {row['Age Group Targeted']} age group. "
        f"It is priced at ${row['Price']}. "
        f"The game has an estimated length of {row['Game Length (Hours)']} hours. "
        f"It requires a minimum of {row['Min Number of Players']} players, "
        f"featuring an {row['Game Mode']} mode (Multiplayer: {row['Multiplayer']}). "
        f"Requires special device: {row['Requires Special Device']}. "
        f"Technically, it offers {row['Graphics Quality']} graphics, "
        f"an {row['Soundtrack Quality']} soundtrack, and a {row['Story Quality']} story. "
        f"It has a user rating of {row['User Rating']}/5. "
        f"An example of an user review would be this one: {row['User Review Text']}"
    )

dataset['Representation_dict'] = dataset.apply(create_dict_string, axis=1)
dataset['Representation_text'] = dataset.apply(create_text_string, axis=1)

#We show each for the first game as an example
print(f"Dict: {dataset['Representation_dict'].iloc[0]}")
print(f"Text: {dataset['Representation_text'].iloc[0]}")

Dict: Title: Grand Theft Auto V,User Rating: 3.6399999999999997/5,Target Audience: All Ages,Price: $41.41,Platform: PC,Requires Special Device: No,Developer: Game Freak,Publisher: Innersloth,Release Year: 2015,Genre: Adventure,Multiplayer: No,Game Length: 55.3 hours,Graphics Quality: Medium,Soundtrack Quality: Average,Story Quality: Poor,Game Mode: Offline,Minimum Players: 1.User Review: Solid game, but too many bugs.
Text: Grand Theft Auto V is a Adventure game for PC, it was released in 2015 by the developer Game Freak and the publisher Innersloth. It is targeted towards the All Ages age group. It is priced at $41.41. The game has an estimated length of 55.3 hours. It requires a minimum of 1 players, featuring an Offline mode (Multiplayer: No). Requires special device: No. Technically, it offers Medium graphics, an Average soundtrack, and a Poor story. It has a user rating of 3.6399999999999997/5. An example of an user review would be this one: Solid game, but too many bugs.

# 4. Baselines tradicionales

Debéis implementar **uno o varios modelos tradicionales** con los que comparar.

## Posibles opciones

### Opción A — Baseline muy sencillo
Un sistema simple por:
- popularidad,
- rating medio,
- weighted rating,
- frecuencia de consumo,
- score heurístico.

### Opción B — Baseline content-based clásico
Un sistema basado en:
- TF-IDF + cosine similarity,
- CountVectorizer + cosine similarity,
- metadata soup clásica.

### Opción C — Baseline colaborativo
Si vuestro dataset tiene interacciones usuario–ítem:
- user-based CF,
- item-based CF,
- kNN,
- SVD / matrix factorization.

## Qué esperamos

No os limitéis a “ejecutar una librería”.

Explicad:
- qué hace el baseline,
- por qué es razonable,
- y por qué es una referencia justa frente al modelo moderno.

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("Training traditional baseline (TF-IDF)(Term Frequency-Inverse Document Frequency)")

#We ignore the unnecessariy words in English (the, a, and, or...)
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

#We create a big matrix weighting each word in our game description
tfidf_matrix = tfidf_vectorizer.fit_transform(dataset['Representation_text'])

#We create a similarity matrix 
cosine_sim_baseline = cosine_similarity(tfidf_matrix, tfidf_matrix)

print("Traditional baseline (TF-IDF) created succesfully")

Training traditional baseline (TF-IDF)(Term Frequency-Inverse Document Frequency)
Traditional baseline (TF-IDF) created succesfully

In [18]:
# Espacio de trabajo: baseline 1

In [19]:
# Espacio de trabajo: baseline 2 (opcional pero recomendado)

# 5. Recomendador basado en embeddings modernos

Implementad aquí vuestro modelo principal.

## Posibles estrategias

### Estrategia 1 — Ítem a ítem
- obtenéis embeddings de todos los ítems,
- calculáis similitud,
- y recomendáis los más cercanos.

### Estrategia 2 — Perfil de usuario
- agregáis embeddings de ítems consumidos / valorados positivamente,
- construís un embedding de usuario,
- y recomendáis por cercanía.

### Estrategia 3 — Query semántica
- representáis una necesidad del usuario como texto,
- la convertís a embedding,
- y recuperáis ítems cercanos.

### Estrategia 4 — Híbrido
- usáis embeddings para recuperar candidatos,
- y luego reordenáis con otra señal:
  popularidad, rating, collaborative score, filtros de negocio, etc.

## Qué debéis justificar

- modelo o servicio usado para obtener embeddings,
- coste / velocidad / facilidad de uso,
- dimensión de embeddings,
- función de similitud,
- si normalizáis o no,
- cómo hacéis retrieval,
- y por qué vuestra decisión tiene sentido para el dataset elegido.

In [20]:
# Espacio de trabajo: generación de embeddings
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import normalize

# generate embedding
print("Loading embedding model...")
model = SentenceTransformer("all-MiniLM-L6-v2")   # lightweight, fast

print("Generating embeddings...")
embeddings = model.encode(dataset["Representation_text"], show_progress_bar=True)

# ensures that cosine similarity is computed correctly
embeddings = normalize(embeddings)

# compare similarities with cosine (the std)
print("Computing similarity matrix (embeddings)...")
cosine_sim_embeddings = cosine_similarity(embeddings, embeddings)

print("Embedding-based recommender ready")

c:\Users\Javi\miniconda3\envs\TODO\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Loading embedding model...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1866.49it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Generating embeddings...

Batches: 100%|██████████| 313/313 [07:23<00:00,  1.42s/it]

Computing similarity matrix (embeddings)...
Embedding-based recommender ready

In [21]:
# Espacio de trabajo: recomendador con embeddings
def recommend_embeddings(game_title, dataset, sim_matrix, top_k=10):
    
    # Get index of the game
    idx = dataset[dataset["Game Title"] == game_title].index[0]
    
    # Get similarity scores
    scores = list(enumerate(sim_matrix[idx]))
    
    # Sort by similarity
    scores = sorted(scores, key=lambda x: x[1], reverse=True)
    
    # Remove the game itself
    scores = scores[1:top_k+1]
    
    # Get indices
    game_indices = [i[0] for i in scores]
    
    return dataset["Game Title"].iloc[game_indices]

We use the all-MiniLM-L6-v2 model to generate 384-dimensional embeddings for each item. Cosine similarity is used to compare items, and embeddings are normalized to improve stability. Recommendations are generated by computing pairwise similarities and retrieving the most similar items. This approach is efficient and suitable for the dataset, which contains rich item descriptions but no user interaction data.

# 6. Diseño de la evaluación

Esta sección es clave.

Una práctica de recomendación no se defiende solo con ejemplos bonitos. Necesitáis un protocolo experimental razonable.

## Preguntas guía

### 1. ¿Qué vais a evaluar exactamente?
- predicción de rating,
- ranking top-N,
- recuperación de ítems relevantes,
- similitud semántica útil,
- utilidad para usuario,
- o una combinación.

### 2. ¿Cómo vais a construir train/test?
Algunas posibilidades:
- split aleatorio,
- leave-one-out por usuario,
- temporal split,
- ocultar interacciones,
- evaluación de recuperación sobre ítems conocidos,
- o escenarios simulados.

### 3. ¿Qué métricas usaréis?
Dependiendo del caso, podrían tener sentido:
- Precision@k,
- Recall@k,
- MAP@k,
- MRR,
- NDCG@k,
- Hit Rate@k,
- RMSE / MAE,
- cobertura,
- diversidad,
- novedad,
- serendipia,
- tiempo de cómputo.

## Requisito obligatorio

Debéis **investigar y justificar** por qué vuestras métricas son adecuadas para vuestro problema.

No aceptaremos una métrica elegida “porque sí”.

## Pregunta central

Al terminar esta sección deberíais poder responder con honestidad:

> ¿Hay evidencia de mejora real frente al baseline?

In [ ]:
import numpy as np
import pandas as pd

SAMPLE_SIZE = 50 
TOP_K = 5       
np.random.seed(10)

juegos_unicos = dataset['Game Title'].unique()
juegos_test = np.random.choice(juegos_unicos, size=min(SAMPLE_SIZE, len(juegos_unicos)), replace=False)

print(f"✅ Protocolo preparado.")
print(f"-> Evaluaremos {len(juegos_test)} juegos 'semilla'.")
print(f"-> Analizaremos las {TOP_K} primeras recomendaciones para cada uno.")
print(f"-> Muestra de los primeros 3 juegos de test: {juegos_test[:3]}")

✅ Protocolo preparado.
-> Evaluaremos 40 juegos 'semilla'.
-> Analizaremos las 5 primeras recomendaciones para cada uno.
-> Muestra de los primeros 3 juegos de test: ['Minecraft' 'Halo Infinite' 'Red Dead Redemption 2']

In [23]:
# Espacio de trabajo: cálculo de métricas

# Listas para guardar las notas de cada iteración
precision_base, diversidad_base = [], []
precision_emb, diversidad_emb = [], []

# Función auxiliar para obtener los índices del top-K (filtrando el juego original)
def get_top_k_indices(game_title, data, sim_matrix, k):
    idx = data[data["Game Title"] == game_title].index[0]
    scores = sorted(list(enumerate(sim_matrix[idx])), key=lambda x: x[1], reverse=True)
    
    rec_indices = []
    for i, score in scores:
        titulo = data["Game Title"].iloc[i]
        # Evitamos recomendar el mismo juego o reseñas duplicadas del mismo juego
        if titulo != game_title and titulo not in [data["Game Title"].iloc[x] for x in rec_indices]:
            rec_indices.append(i)
        if len(rec_indices) == k:
            break
    return rec_indices

print("Calculando métricas... ⏳")

# Bucle principal de evaluación
for juego in juegos_test:
    # Obtenemos la etiqueta "real" (Ground Truth) de nuestro juego semilla
    idx_real = dataset[dataset["Game Title"] == juego].index[0]
    genero_real = dataset["Genre"].iloc[idx_real]
    
    # --- EVALUAR BASELINE (TF-IDF) ---
    idx_b = get_top_k_indices(juego, dataset, cosine_sim_baseline, TOP_K)
    generos_b = dataset["Genre"].iloc[idx_b].tolist()
    devs_b = dataset["Developer"].iloc[idx_b].tolist()
    
    # Precision: ¿Cuántos del top 5 comparten el género original?
    precision_base.append(sum(1 for g in generos_b if g == genero_real) / TOP_K)
    # Diversidad: ¿Cuántos desarrolladores distintos hay en el top 5?
    diversidad_base.append(len(set(devs_b)) / TOP_K)
    
    # --- EVALUAR EMBEDDINGS MODERNOS ---
    idx_e = get_top_k_indices(juego, dataset, cosine_sim_embeddings, TOP_K)
    generos_e = dataset["Genre"].iloc[idx_e].tolist()
    devs_e = dataset["Developer"].iloc[idx_e].tolist()
    
    precision_emb.append(sum(1 for g in generos_e if g == genero_real) / TOP_K)
    diversidad_emb.append(len(set(devs_e)) / TOP_K)

# Creamos la tabla final con las medias de los 50 juegos
resultados_evaluacion = pd.DataFrame({
    'Métrica': [f'Precision@{TOP_K} (Acierto de Género)', f'Diversidad@{TOP_K} (Desarrolladores Únicos)'],
    'Baseline (TF-IDF)': [f"{np.mean(precision_base):.2%}", f"{np.mean(diversidad_base):.2%}"],
    'Embeddings (MiniLM)': [f"{np.mean(precision_emb):.2%}", f"{np.mean(diversidad_emb):.2%}"]
})

print("\n🏆 RESULTADOS DE LA EVALUACIÓN 🏆")
print("-" * 50)
print(resultados_evaluacion.to_markdown(index=False))

Calculando métricas... ⏳

🏆 RESULTADOS DE LA EVALUACIÓN 🏆
--------------------------------------------------
| Métrica                               | Baseline (TF-IDF)   | Embeddings (MiniLM)   |
|:--------------------------------------|:--------------------|:----------------------|
| Precision@5 (Acierto de Género)       | 33.00%              | 46.50%                |
| Diversidad@5 (Desarrolladores Únicos) | 69.00%              | 78.50%                |

# 7. Comparación cualitativa

Además de los números, mostrad ejemplos concretos.

## Qué incluir

Para varios casos de prueba, enseñad:
- recomendaciones del baseline,
- recomendaciones del modelo con embeddings,
- y comentario crítico sobre las diferencias.

## Preguntas útiles

- ¿El modelo con embeddings captura mejor matices semánticos?
- ¿Recomienda cosas demasiado obvias?
- ¿Introduce variedad útil?
- ¿Se deja engañar por ruido textual?
- ¿Empeora cuando faltan metadatos?
- ¿Se parece demasiado a un buscador semántico en vez de a un recomendador?

In [28]:
# Espacio de trabajo: comparación cualitativa de recomendaciones

def comparar_modelos_cualitativamente(juego, dataset, baseline_matrix, embeddings_matrix, top_k=5):
    print(f"🎮 CASO DE ESTUDIO: {juego}")
    print("="*70)
    
    # Baseline
    idx_b = get_top_k_indices(juego, dataset, baseline_matrix, top_k)
    res_b = dataset.iloc[idx_b][['Game Title', 'Genre', 'Developer']]
    print("▶️ RECOMENDACIONES BASELINE (TF-IDF):")
    print(res_b.to_string(index=False))
    
    # Embeddings
    print("\n▶️ RECOMENDACIONES EMBEDDINGS (MiniLM):")
    idx_e = get_top_k_indices(juego, dataset, embeddings_matrix, top_k)
    res_e = dataset.iloc[idx_e][['Game Title', 'Genre', 'Developer']]
    print(res_e.to_string(index=False))
    print("\n")

# Ejecuta esto con 3 juegos que te parezcan interesantes
comparar_modelos_cualitativamente("Grand Theft Auto V", dataset, cosine_sim_baseline, cosine_sim_embeddings)
comparar_modelos_cualitativamente("The Sims 4", dataset, cosine_sim_baseline, cosine_sim_embeddings)
comparar_modelos_cualitativamente("Minecraft", dataset, cosine_sim_baseline, cosine_sim_embeddings)

🎮 CASO DE ESTUDIO: Grand Theft Auto V
======================================================================
▶️ RECOMENDACIONES BASELINE (TF-IDF):
     Game Title     Genre  Developer
       Tekken 7     Party Game Freak
Half-Life: Alyx Adventure Game Freak
       Hitman 3 Adventure Innersloth
       Among Us  Strategy Game Freak
     The Sims 4 Adventure Game Freak

▶️ RECOMENDACIONES EMBEDDINGS (MiniLM):
                             Game Title     Genre      Developer
                               Among Us Adventure Rockstar Games
            Sid Meier’s Civilization VI Adventure     Innersloth
The Legend of Zelda: Breath of the Wild  Strategy     Innersloth
                               Fortnite Adventure       Nintendo
                       Street Fighter V Adventure     Epic Games


🎮 CASO DE ESTUDIO: The Sims 4
======================================================================
▶️ RECOMENDACIONES BASELINE (TF-IDF):
              Game Title     Genre  Developer
                Fortnite     Party Epic Games
       League of Legends   Shooter     Bungie
The Witcher 3: Wild Hunt Adventure      Valve
       1000-Piece Puzzle  Fighting  EA Sports
                 FIFA 24       RPG Game Freak

▶️ RECOMENDACIONES EMBEDDINGS (MiniLM):
                             Game Title      Genre      Developer
                               Among Us Simulation Rockstar Games
                              Minecraft Simulation          Valve
The Legend of Zelda: Breath of the Wild Simulation Rockstar Games
                        Just Dance 2024 Simulation     Game Freak
            Sid Meier’s Civilization VI Simulation     Game Freak


🎮 CASO DE ESTUDIO: Minecraft
======================================================================
▶️ RECOMENDACIONES BASELINE (TF-IDF):
Game Title     Genre      Developer
    Tetris Adventure         Bungie
  Portal 2    Sports CD Projekt Red
The Sims 4 Adventure         Capcom
  Hitman 3   Shooter         Bungie
   Cuphead    Sports         Capcom

▶️ RECOMENDACIONES EMBEDDINGS (MiniLM):
                             Game Title     Genre      Developer
                               Among Us Adventure Rockstar Games
The Legend of Zelda: Breath of the Wild  Strategy       Nintendo
                      League of Legends Adventure          Valve
                                FIFA 24 Adventure      EA Sports
                        Half-Life: Alyx Adventure     Game Freak

- ¿El modelo con embeddings captura mejor matices semánticos?

Absolutely, since a TF-IDF only captures exact shared words while an embedding model can use context to detect that two synonyms actually mean the same, despite not being the same word.

- ¿Recomienda cosas demasiado obvias?
Not at all, it simply detects similar games based off same context similarities.


- ¿Introduce variedad útil?
Absolutely, as it won't only take into account one variable for each game, but it will contextualize multiple.


- ¿Se deja engañar por ruido textual?
It doesn't, which is probably the biggest advantage it has over the TF-IDF, which is heavily influenced by it.


- ¿Empeora cuando faltan metadatos?
It obviously does. However, it's still more resilient to the lack of metadata than the traditional models.


- ¿Se parece demasiado a un buscador semántico en vez de a un recomendador?
This is probably the only weak spot in our model, as it is indeed pretty similar to a semantic search in some aspects, such as the fact that it will group games with similar reviews even if the review is just "bad game", where our model would group bad games, not similar games

# 8. Retos, limitaciones y discusión

En esta práctica no buscamos solo un resultado “bonito”.

Queremos también pensamiento crítico.

## Debéis discutir, al menos, algunos de estos puntos

- sensibilidad a cómo construís el texto,
- dependencia de la calidad del dataset,
- ruido en categorías / tags / descripciones,
- coste de generar embeddings,
- escalabilidad,
- problema de cold start,
- necesidad o no de interacción usuario–ítem,
- interpretabilidad,
- sesgo hacia popularidad,
- sesgo hacia similitud superficial,
- dificultad para evaluar offline,
- y posibles riesgos de sobreinterpretar pequeñas mejoras.

## Pregunta importante

¿En qué escenarios pensáis que el enfoque con embeddings modernos **sí** tiene ventaja clara?

¿Y en cuáles un método más clásico puede seguir siendo:
- suficiente,
- más barato,
- más interpretable,
- o incluso mejor?

- The performance of the model is highly sensitive to how the input text is constructed. The model is also affected by noisy textual data, which can lead to misleading similarities, therefore missing or inconsistent metadata reduces recommendation quality. Embedding models are also computationally more expensive than traditional methods, since computing a full similarity matrix has a higher complexity and can cause memory issues. Although the system works, it lacks personalization, as it is purely item-to-item and does not consider user preferences since it uses a semantic search engine, grouping items based on similar wording rather than true similarity. Another limitation is that the evaluation is limited because there is no real user interaction data, metrics like genre matching are only approximations.

- Embedding-based approaches have a clear advantage when the dataset contains rich textual information and semantic similarity is important. They are especially useful when there is no user–item interaction data available, as they can still generate meaningful recommendations based on context. This makes them ideal for scenarios focused on discovery and exploration, since understanding the meaning behind descriptions is more important than word matching.

- On the other hand, traditional methods can still be better in differeny situations. For small datasets, simpler models like TF-IDF can perform well with much lower computational cost. They are also more interpretable, since recommendations can be explained through shared keywords. Finally, in systems where efficiency and scalability are critical, classical approaches are often more practical and easier to deploy.

# 9. Conclusiones

Cerrad el trabajo con una conclusión breve pero sólida.

## Debe responder, como mínimo, a estas preguntas

1. ¿Qué habéis construido?
2. ¿Con qué lo habéis comparado?
3. ¿Cuál ha funcionado mejor y según qué métricas?
4. ¿Qué habéis aprendido sobre diseñar recomendadores con embeddings?
5. ¿Qué mejoraríais si tuvierais más tiempo?

In [26]:
# TODO: conclusiones finales

# Entregables

## Entrega obligatoria

Debéis entregar:

1. **Este notebook** completo y ejecutable.
2. Los ficheros auxiliares necesarios para reproducir el experimento.
3. Un **README breve** con:
   - dataset usado,
   - instrucciones de ejecución,
   - dependencias,
   - y resumen de resultados.
4. Una breve sección final o anexo con:
   - retos,
   - limitaciones,
   - y líneas futuras.

## Reproducibilidad

El notebook debe poder entenderse y ejecutarse con claridad.

No hace falta que todo sea perfecto, pero sí que:
- el flujo tenga sentido,
- las decisiones estén justificadas,
- y las conclusiones estén apoyadas por resultados.

# Criterios de evaluación sugeridos

## 1. Planteamiento del problema
- claridad del objetivo,
- adecuación del dataset,
- coherencia del escenario de recomendación.

## 2. Calidad del pipeline
- limpieza,
- preparación,
- construcción de la representación,
- reproducibilidad.

## 3. Baselines
- que existan,
- que sean razonables,
- y que la comparación sea justa.

## 4. Modelo con embeddings
- calidad de la idea,
- corrección de la implementación,
- justificación técnica.

## 5. Evaluación
- calidad del protocolo,
- elección de métricas,
- rigor del análisis.

## 6. Discusión crítica
- interpretación honesta,
- identificación de limitaciones,
- propuestas de mejora.

## 7. Comunicación
- notebook claro,
- figuras o tablas útiles,
- redacción limpia,
- conclusiones comprensibles.

# Pistas y consejos

## Consejo 1
No intentéis construir el recomendador “más complejo posible” desde el minuto uno.

Primero haced que funcione un baseline simple y un pipeline básico.

## Consejo 2
En recomendación, muchas veces una gran parte del rendimiento depende de:
- cómo definís el problema,
- cómo preparáis los datos,
- y cómo evaluáis.

## Consejo 3
Las mejoras pequeñas pueden ser reales… o ruido experimental.

Sed prudentes al interpretar resultados.

## Consejo 4
No confundáis:
- similitud semántica,
- recomendación útil,
- ranking,
- y predicción de preferencia.

Están relacionados, pero no son exactamente lo mismo.

## Consejo 5
Una muy buena práctica es incluir una pequeña tabla resumen final con:
- modelo,
- representación usada,
- métricas,
- ventajas,
- limitaciones.

# Extensiones opcionales

Si queréis subir nivel, podéis intentar alguna de estas extensiones:

- usar varias estrategias de construcción del string y compararlas,
- hacer un pequeño estudio de ablación,
- combinar embeddings con popularidad o collaborative filtering,
- añadir reranking,
- estudiar diversidad y cobertura además de precisión,
- crear una demo sencilla,
- analizar fallos,
- o proponer una versión para producción.

# Cierre

## Mensaje final

El objetivo de esta práctica no es demostrar que “lo moderno siempre gana”.

El objetivo es aprender a responder con datos, método y criterio a una pregunta muy real en sistemas de recomendación:

> **¿Cuándo merece la pena pasar de un enfoque clásico a uno basado en embeddings modernos?**

Buena suerte, y defended vuestras decisiones con claridad.